title: Héctor Mejía # your name (or website title) here
logo: "/images/WIN_20211001_12_16_02_Pro.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist, CDMX, México
  <br><br>
  Mi objetivo es: Desarrollar e implementar modelos de ML para mitigar riesgos de crédito y fraude
  <br><br>
  Tengo experiencia en: Riesgo de crédito, Fraudes
  <br><br>
  <a href="https://www.linkedin.com/in/hector-d-mejia">Entra a mi perfil de LinkedIn</a> 

  
theme: jekyll-theme-minimal
